name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs_site/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:  # Allow manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files in docs_site directory:"
          ls -la docs_site || echo "docs_site directory not found"
          echo "Files in docs_site/docs directory:"
          ls -la docs_site/docs || echo "docs_site/docs directory not found"
          echo "Content of mkdocs.yml:"
          cat mkdocs.yml
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Build docs (debug)
        run: |
          mkdocs build --verbose
          echo "Built site files:"
          ls -la site/
      
      - name: Deploy docs
        run: |
          # Use custom deploy to be more explicit
          # Create gh-pages branch if it doesn't exist
          git checkout -B gh-pages
          
          # Remove existing files
          rm -rf ./* || true
          
          # Copy built website files
          cp -r site/* ./
          
          # Add .nojekyll file to prevent GitHub Pages from processing with Jekyll
          touch .nojekyll
          
          # Add all files, commit and push
          git add -A
          git commit -m "Deploy documentation updates" || echo "No changes to commit"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 