name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    - name: Load cached venv
      id: cached-uv-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
    - name: Install dependencies
      if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
      run: |
        uv venv
        uv pip install -e ".[dev]"
    - name: Activate virtual environment
      run: source .venv/bin/activate
    - name: Run black
      run: uv run black . --check --line-length 200 --exclude .venv
    - name: Run isort
      run: uv run isort . --check-only --profile black --line-length 200 --skip .venv
    - name: Run flake8
      run: uv run flake8 . --max-line-length=200 --ignore=E266,W503,E203 --exclude=.venv
    - name: Run mdformat
      run: |
        uv run mdformat README.md --check
        uv run mdformat docs_site/docs --check 